version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        env: "prod"
    ports:
      - 80:80
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
