version: "3.3"
services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:dev
    environment:
        env: "dev"
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:dev
    environment:
        env: "prod"
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
