version: "3.3"
services:
  xcodereleases:
    build: .
    restart: always
    image: jefflett/xcodereleases
    ports:
      - 8080:8080
    volumes:
      - ../XcodeReleasesData:/var/lib/xcodereleases/data
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - BUNDLE_IDENTIFIER=com.jefflett.XcodeReleases
      - PUSH_DEV_CERTIFICATE_PATH=/var/lib/xcodereleases/data/DevPushCert.pem
      - PUSH_CERTIFICATE_PATH=/var/lib/xcodereleases/data/PushCert.pem
      - PUSH_CERTIFICATE_PWD=
      - PUSH_DEV_CERTIFICATE_PWD=

