version: "3.3"
services:
  api:
    build: .
    restart: always
    image: xcodereleases:latest
    environment:
        env: "prod"
    ports:
      - 80:80
    volumes:
      - .:/app
      - ../XcodeReleasesData:/var/lib/xcodereleases/data
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
