version: "3.3"
services:
  xcodereleases:
    build: .
    restart: always
    image: jefflett/xcodereleases
    ports:
      - 8080:8080
    volumes:
      - ../XcodeReleasesData:/var/lib/xcodereleases/data
    working_dir: /app
    stdin_open: true
    tty: true
